# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('infocard', models.TextField()),
                ('price', models.BigIntegerField()),
                ('max_bats', models.IntegerField()),
                ('max_bots', models.IntegerField()),
                ('hitpoints', models.BigIntegerField()),
                ('hold_size', models.IntegerField()),
                ('weapon_angle', models.IntegerField()),
                ('mass', models.BigIntegerField()),
                ('torgue_x', models.FloatField()),
                ('torgue_y', models.FloatField()),
                ('torgue_z', models.FloatField()),
                ('drag_x', models.FloatField()),
                ('drag_y', models.FloatField()),
                ('drag_z', models.FloatField()),
                ('inerta_x', models.FloatField()),
                ('inerta_y', models.FloatField()),
                ('inerta_z', models.FloatField()),
                ('nudge', models.FloatField()),
                ('strafe', models.IntegerField()),
                ('strafe_power', models.IntegerField()),
                ('linear_drag', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipModelLOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lod_name', models.CharField(max_length=10)),
                ('vertices', models.BinaryField()),
                ('normals', models.BinaryField()),
                ('uvs', models.BinaryField()),
                ('materials', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tex_id', models.IntegerField()),
                ('ix', models.IntegerField()),
                ('iy', models.IntegerField()),
                ('inversion', models.BooleanField()),
                ('texture', models.BinaryField()),
            ],
        ),
        migrations.AddIndex(
            model_name='texture',
            index=models.Index(fields=['tex_id'], name='api_texture_tex_id_d5a35a_idx'),
        ),
        migrations.AddField(
            model_name='shipmodellod',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ship'),
        ),
        migrations.AddField(
            model_name='shipcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ShipCategory'),
        ),
        migrations.AddField(
            model_name='ship',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ShipCategory'),
        ),
        migrations.AddIndex(
            model_name='shipmodellod',
            index=models.Index(fields=['ship', 'lod_name'], name='api_shipmod_ship_id_34812e_idx'),
        ),
        migrations.AddIndex(
            model_name='shipcategory',
            index=models.Index(fields=['parent_category'], name='api_shipcat_parent__dc214f_idx'),
        ),
        migrations.AddIndex(
            model_name='ship',
            index=models.Index(fields=['category'], name='api_ship_categor_348198_idx'),
        ),
    ]
