# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipcategory',
            name='backgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='shipcategory',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='mass',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shipcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
