# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170930_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipcategory',
            old_name='backgroundImage',
            new_name='background_image',
        ),
    ]
