# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170930_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipcategory',
            options={'verbose_name': 'Ship category', 'verbose_name_plural': 'Ship categories'},
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='inerta_x',
            new_name='inertia_x',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='inerta_y',
            new_name='inertia_y',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='inerta_z',
            new_name='inertia_z',
        ),
    ]
