# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def cleanup_all_ships(apps, schema_editor):
    Texture = apps.get_model('api', 'Texture')
    Ship = apps.get_model('api', 'Ship')

    Ship.objects.all().delete()
    Texture.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171001_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='TexturePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='shipcategory',
            options={'ordering': ['parent_category', 'name'], 'verbose_name': 'Ship category', 'verbose_name_plural': 'Ship categories'},
        ),
        migrations.AddField(
            model_name='ship',
            name='textures',
            field=models.ManyToManyField(to='api.TexturePack'),
        ),
        migrations.AddField(
            model_name='texture',
            name='texture_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TexturePack'),
        ),
        migrations.RunPython(
            cleanup_all_ships,
            migrations.RunPython.noop,
        )
    ]
