# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171004_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipcategory',
            options={'ordering': ['parent_category_id', 'name'], 'verbose_name': 'Ship category', 'verbose_name_plural': 'Ship categories'},
        ),
    ]
