# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171004_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipcategory',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='shipcategory',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/logos/'),
        ),
    ]
