# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171007_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmodellod',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='shipmodellod',
            name='normals',
        ),
        migrations.RemoveField(
            model_name='shipmodellod',
            name='uvs',
        ),
        migrations.RemoveField(
            model_name='shipmodellod',
            name='vertices',
        ),
        migrations.RemoveField(
            model_name='texture',
            name='inversion',
        ),
        migrations.RemoveField(
            model_name='texture',
            name='ix',
        ),
        migrations.RemoveField(
            model_name='texture',
            name='iy',
        ),
        migrations.RemoveField(
            model_name='texture',
            name='texture',
        ),
    ]
